/**
 * Static facts about each feed source (`source_info` tool): publisher, API, human page, licence and attribution,
 * cadence, latency, rate limit, coverage limits, and what the feed can and cannot tell us. From the adapters'
 * docs (`api/src/ingest/poll/*.rs`, `docs/ingest-modes.md`, `docs/evidence/carp-data-proof.md`). No network.
 */

export type SourceFacts = {
  feed: string;
  publisher: string;
  apiUrl: string;
  pageUrl: string;
  licence: string;
  attribution: string;
  cadence: string;
  latency: string;
  rateLimit: string;
  coverage: string;
  limits: string[];
  /** What the feed tells us, in operational terms. */
  tells: string;
  /** How to name the feed in an answer. */
  sayAs?: string;
  /** Feeds that belong in the same answer (an archive and the live source it copies). */
  related?: string[];
};

export const SOURCE_FACTS: Record<string, SourceFacts> = {
  usgs: {
    feed: "usgs",
    publisher: "U.S. Geological Survey, Water Data for the Nation",
    apiUrl: "https://api.waterdata.usgs.gov/ogcapi/v0/collections/continuous/items",
    pageUrl: "https://waterdata.usgs.gov/",
    licence: "U.S. Government work, public domain (no licence needed); provisional data subject to revision",
    attribution: "Data from the U.S. Geological Survey (USGS Water Data for the Nation)",
    cadence: "15-minute instantaneous values; polled every 15 minutes, all gauges in one request",
    latency: "about 20 to 70 minutes from measurement to availability",
    rateLimit: "not published for the OGC API; anonymous use is throttled, so one batched request per poll",
    coverage: "gage height (stage, ft, stored in metres) at every demonstration gauge; discharge (cfs) only where the gauge rates flow",
    limits: [
      "no discharge at Krotz Springs (07381500), Butte La Rose (07381515) and Alexandria (07355500): stage only",
      "stage is on the USGS gage datum, which differs from the NWPS datum at some sites (Krotz Springs reads about 2.45 ft lower), so USGS stage is never compared with flood categories",
      "no push or webhook: WaterAlert sends email or text to a person, not data to a machine",
      "values are provisional and can be revised; -999999 means no value",
    ],
    tells: "observed river stage and discharge history: how high the river is and how it changed; it does not say anything about carp, catch, access or safety",
    related: ["nwps"],
  },
  nwps: {
    feed: "nwps",
    publisher: "NOAA National Weather Service, National Water Prediction Service (NWPS), River Forecast Centers",
    apiUrl: "https://api.water.noaa.gov/nwps/v1/gauges/{lid}/stageflow",
    pageUrl: "https://water.noaa.gov/",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA National Water Prediction Service (NWS River Forecast Centers)",
    cadence: "forecast issued about once a day (13Z to 16Z, 08 to 11 Central), more often in flood; observed stage hourly; polled every 30 to 60 minutes",
    latency: "observed values appear about 55 minutes after their valid time; a forecast is captured within an hour of issuance",
    rateLimit: "not published; responses carry no cache headers",
    coverage: "stage (ft, NWPS datum) and flow (kcfs) observed and forecast at the eight demonstration sites; flood categories (action, minor, moderate, major) and low-water threshold from the gauge metadata",
    limits: [
      "no history: the API returns only the current forecast, so past issuances come from our own snapshots or the IEM archive",
      "forecast horizons differ per site: 5 days (Red, Ouachita), 10 days (Pearl), 14 to 15 days (Atchafalaya, Mississippi)",
      "flow thresholds are -9999 (not defined) at most sites; flow at some sites is an NWS estimate, not a USGS measurement",
      "a forecast is a deterministic stage path, not a probability; the feed gives no chance of flooding",
    ],
    tells: "the official river forecast and its flood category per site, and whether the gauge agrees with it; it does not say anything about carp, catch, access or safety",
    sayAs: "NOAA's National Water Prediction Service (NWPS)",
    related: ["iem", "usgs"],
  },
  "nws-alerts": {
    feed: "nws-alerts",
    publisher: "NOAA National Weather Service (api.weather.gov alerts)",
    apiUrl: "https://api.weather.gov/alerts/active?area=LA",
    pageUrl: "https://www.weather.gov/documentation/services-web-api",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA National Weather Service",
    cadence: "statewide active alerts polled every 1 to 2 minutes; matched to sites by polygon or forecast zone and county",
    latency: "about 1 to 2 minutes after the office issues the product",
    rateLimit: "not published; a User-Agent header is required",
    coverage: "every active watch, warning, advisory and statement for Louisiana; each site matched by point or UGC zone",
    limits: [
      "no push: NWWS-OI (XMPP) needs an emailed application, so alerts arrive by poll",
      "zone-based alerts carry no polygon; a site is matched through its forecast zone or county, which can be wider than the site",
      "an empty result means no alert was in effect at the last check, which is itself cited as that check",
    ],
    tells: "whether a flood, wind, storm or other NWS product is in effect at a site, a reason for operational review; it is not a safety verdict",
  },
  "nws-forecast": {
    feed: "nws-forecast",
    publisher: "NOAA National Weather Service (api.weather.gov gridpoint forecast)",
    apiUrl: "https://api.weather.gov/gridpoints/{office}/{x},{y}/forecast (12 h periods) and https://api.weather.gov/gridpoints/{office}/{x},{y} (raw grid)",
    pageUrl: "https://www.weather.gov/documentation/services-web-api",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA National Weather Service",
    cadence: "12-hour periods, 7 days; the office updates its grid a few times a day; polled hourly, versioned on updateTime",
    latency: "updateTime is per office run, not per point; forecasts were 0.6 to 6.5 h old when probed",
    rateLimit: "not published; a User-Agent header is required",
    coverage: "temperature, wind, chance of precipitation per 12 h period, and the raw grid's 6 h precipitation amounts (QPF, mm) and hourly gusts at each site's grid cell",
    limits: [
      "the adapter stores temperature (°F to °C), wind (upper bound of the range, mph to m/s) and the chance of precipitation (percent) per period, plus the raw grid's QPF (mm per 6 h window) and gusts (km/h to m/s); sky text stays in the raw payload",
      "a chance of precipitation is a probability and QPF an amount at the grid cell: neither is a river stage or flood prediction",
      "a point forecast, not a watch or warning: alerts are the nws-alerts feed",
    ],
    tells: "the weather crews will work in (wind, gusts, temperature, rain chance and amount), a reason to plan or review; it does not judge safety",
  },
  iem: {
    feed: "iem",
    publisher: "Iowa Environmental Mesonet, Iowa State University (a university archive of NWS products, not NOAA)",
    apiUrl: "https://mesonet.agron.iastate.edu/cgi-bin/request/hml.py?station={lid}&kind=forecasts&fmt=csv",
    pageUrl: "https://mesonet.agron.iastate.edu/request/hml.php",
    licence: "free for research and operational use with attribution; Iowa State asks not to hammer the service",
    attribution: "Iowa Environmental Mesonet, Iowa State University (archive of NWS HML river forecast products)",
    cadence: "every NWS HML forecast product as issued, archived; polled daily for the last 30 days per site",
    latency: "an issuance appears in the archive within hours; the archive is backfilled once, then topped up daily",
    rateLimit: "not published; cached locally, one request per site per day",
    coverage: "past river forecast issuances per site, back well before our first live capture",
    limits: [
      "a third-party copy: when IEM and our own NWPS snapshot both hold an issuance, the snapshot is the record and IEM the backup",
      "archive rows are known from their issuance time, so a replay shows them as the RFC published them, not as we captured them",
    ],
    tells: "what the river forecast said on a past day: it lets the timeline replay what was known then, and a forecast-versus-actual check go back before our own snapshots began",
    sayAs: "Iowa State University's Iowa Environmental Mesonet (IEM) archive",
    related: ["nwps"],
  },
  aisstream: {
    feed: "aisstream",
    publisher: "AISStream.io (terrestrial AIS receivers)",
    apiUrl: "wss://stream.aisstream.io/v0/stream",
    pageUrl: "https://aisstream.io/documentation",
    licence: "free (beta), no formal terms or SLA; AIS is a public radio broadcast; the key stays on the server",
    attribution: "Vessel positions: AISStream.io",
    cadence: "push (websocket) as ships report; stored at most once per vessel per minute, kept 30 days",
    latency: "seconds after a shore receiver hears the ship",
    rateLimit: "3 connections per account and per IP; one subscription update per second",
    coverage: "ships with AIS transponders inside the app's region boxes, near shore receivers",
    limits: ["only ships that broadcast AIS; small boats often do not", "coverage thins offshore", "off until AISSTREAM_API_KEY is set; stored history still replays"],
    tells: "where ships were and how they moved, as context on the map; it says nothing about carp or lionfish",
  },
  eddmaps: {
    feed: "eddmaps",
    publisher: "Bugwood Center, University of Georgia: EDDMapS (Early Detection and Distribution Mapping System), behind Florida's IveGot1 app",
    apiUrl: "https://api.bugwood.org/rest/api/occurrence",
    pageUrl: "https://www.eddmaps.org/",
    licence: "open, no key; terms of use not confirmed (the developer pages were unreachable when this was added)",
    attribution: "Reports from EDDMapS (Bugwood Center, University of Georgia)",
    cadence: "polled every 30 minutes",
    latency: "reports appear the day they are entered; verified by EDDMapS reviewers",
    rateLimit: "not published; one request per poll",
    coverage: "Burmese python reports in the python app's region; a small set (41 records when added) next to iNaturalist's and NAS's",
    limits: ["few records: it adds recent verified reports, not volume", "some reports repeat iNaturalist or NAS records and are not linked as duplicates"],
    tells: "the freshest verified python reports, often entered the same day",
    sayAs: "EDDMapS (Florida's IveGot1)",
  },
  nwws: {
    feed: "nwws",
    publisher: "NOAA NWS Weather Wire Service Open Interface (NWWS-OI)",
    apiUrl: "xmpp://nwws-oi.weather.gov",
    pageUrl: "https://www.weather.gov/nwws/nwws_oi_request",
    licence: "U.S. Government work, public domain; account by application",
    attribution: "NOAA National Weather Service",
    cadence: "push (XMPP) as products are issued",
    latency: "seconds",
    rateLimit: "account-based",
    coverage: "every NWS text product for the configured offices",
    limits: ["disabled until the application is approved (10 or more days); alerts arrive by poll meanwhile"],
    tells: "the same alerts faster, once approved",
  },
  inat: {
    feed: "inat",
    publisher: "iNaturalist (California Academy of Sciences and National Geographic)",
    apiUrl: "https://api.inaturalist.org/v1/observations",
    pageUrl: "https://www.inaturalist.org/",
    licence: "observations under the licence each observer chose (CC0, CC BY, CC BY-NC, or all rights reserved); metadata open",
    attribution: "iNaturalist observers; link every record to its iNaturalist page",
    cadence: "polled every 5 minutes",
    latency: "minutes after an observer uploads; identifications change for days",
    rateLimit: "about 60 requests per minute, 10,000 per day",
    coverage: "every observation in the region of any species",
    limits: ["reports, not abundance", "quality grades: research, needs ID, casual", "coordinates may be obscured for sensitive taxa"],
    tells: "where people reported an animal and when",
  },
  nas: {
    feed: "nas",
    publisher: "USGS Nonindigenous Aquatic Species database",
    apiUrl: "https://nas.er.usgs.gov/api/v2/occurrence/search",
    pageUrl: "https://nas.er.usgs.gov/",
    licence: "U.S. Government work, public domain",
    attribution: "U.S. Geological Survey Nonindigenous Aquatic Species Database",
    cadence: "polled hourly",
    latency: "curated records lag the observation by weeks to months (late records; outside Florida by months to years)",
    rateLimit: "not published",
    coverage: "verified nonindigenous species occurrences; not US-only (Mexico, Belize and Colombia records exist), but outside Florida the newest records lag months to years (Colombia's newest lionfish record is from 2016)",
    limits: ["late by design: curated weeks to months after the observation", "many records duplicate iNaturalist reports", "stale outside Florida"],
    tells: "curated, verified sightings that arrive late; history and corroboration, never the latest word",
  },
  gbif: {
    feed: "gbif",
    publisher: "Global Biodiversity Information Facility",
    apiUrl: "https://api.gbif.org/v1/occurrence/search",
    pageUrl: "https://www.gbif.org/",
    licence: "CC0 and CC BY per dataset",
    attribution: "GBIF.org and the publishing datasets",
    cadence: "polled hourly",
    latency: "days to weeks (datasets publish in batches)",
    rateLimit: "fair use",
    coverage: "aggregated occurrence records from many datasets (iNaturalist research grade, REEF surveys, museums, NAS mirrors)",
    limits: ["duplicates: its copies of iNaturalist research-grade records are matched by catalogue number and never counted as corroboration (deduplicated against iNaturalist)", "late: datasets publish in weekly batches, days to weeks after the observation", "history rather than news"],
    tells: "the long record (history) of where lionfish were found, and a second source only where a record is not a duplicate of an iNaturalist report",
  },
  ndbc: {
    feed: "ndbc",
    publisher: "NOAA National Data Buoy Center",
    apiUrl: "https://www.ndbc.noaa.gov/data/realtime2/{station}.txt",
    pageUrl: "https://www.ndbc.noaa.gov/",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA National Data Buoy Center",
    cadence: "hourly or 10-minute; polled every 10 minutes",
    latency: "about an hour",
    rateLimit: "not published",
    coverage: "buoy water temperature, waves, wind; sea-temperature buoys exist only in Florida among the lionfish areas (none in the Mexican Caribbean, Belize or Colombia)",
    limits: ["buoys go offline for weeks", "measured in situ: preferred over satellite", "no buoy outside Florida, so satellite SST cannot be checked there"],
    tells: "measured sea temperature and sea state where a buoy exists",
  },
  coops: {
    feed: "coops",
    publisher: "NOAA CO-OPS Tides and Currents",
    apiUrl: "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter",
    pageUrl: "https://tidesandcurrents.noaa.gov/",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA CO-OPS",
    cadence: "6-minute; polled every 10 minutes",
    latency: "minutes",
    rateLimit: "not published",
    coverage: "water level, water temperature at tide stations",
    limits: ["few stations"],
    tells: "measured water level and temperature at the coast",
  },
  openmeteo: {
    feed: "openmeteo",
    publisher: "Open-Meteo (open-source weather API)",
    apiUrl: "https://api.open-meteo.com/v1/forecast",
    pageUrl: "https://open-meteo.com/",
    licence: "CC BY 4.0 (non-commercial free tier)",
    attribution: "Weather data by Open-Meteo.com",
    cadence: "hourly; polled hourly",
    latency: "model run cycle, hours",
    rateLimit: "10,000 requests per day on the free tier",
    coverage: "modelled air temperature, rain, wind on a grid",
    limits: ["modelled, not measured"],
    tells: "modelled weather where no station is",
  },
  "openmeteo-marine": {
    feed: "openmeteo-marine",
    publisher: "Open-Meteo Marine API (open-source weather API; MeteoFrance wave and current models)",
    apiUrl: "https://marine-api.open-meteo.com/v1/marine",
    pageUrl: "https://open-meteo.com/en/docs/marine-weather-api",
    licence: "CC BY 4.0 attribution; the free tier is for non-commercial use only (a commercial deployment needs a paid API key)",
    attribution: "Weather data by Open-Meteo.com",
    cadence: "hourly values, 72 h horizon; polled hourly per forecast point",
    latency: "model run cycle, hours; the run time is not stored, the fetch time is",
    rateLimit: "10,000 requests per day on the free tier",
    coverage: "modelled wave height (m), wave period (s), ocean current velocity (published in km/h, stored in m/s) and direction at reef points of the four areas",
    limits: ["modelled, not measured: no buoy checks it outside Florida", "72 hours ahead, nothing beyond", "field conditions for planning dives: never part of the survey priority"],
    tells: "whether the sea will let a team dive a reef in the next three days; it says nothing about lionfish or priority",
    sayAs: "Open-Meteo Marine",
  },
  goes19: {
    feed: "goes19",
    publisher: "NOAA GOES-19 (ABI land surface temperature, fire)",
    apiUrl: "s3://noaa-goes19 (push via SQS)",
    pageUrl: "https://registry.opendata.aws/noaa-goes/",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA GOES-R series",
    cadence: "every 10 minutes (push)",
    latency: "minutes",
    rateLimit: "none (object storage)",
    coverage: "satellite land surface temperature and fire radiative power on a 2 km grid over the whole region, every 10 minutes: values between and beyond the weather stations, not only at them",
    limits: ["cloud gaps: a cloud-masked pixel has no value", "satellite skin temperature, not air temperature"],
    tells: "satellite temperature for every grid cell where clouds allow, so the activity rule has a value away from the stations",
  },
  "goes19-sst": {
    feed: "goes19-sst",
    publisher: "NOAA GOES-19 sea surface temperature (ABI L2 SSTF, full disk)",
    apiUrl: "s3://noaa-goes19/ABI-L2-SSTF (push via SQS)",
    pageUrl: "https://registry.opendata.aws/noaa-goes/",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA GOES-R series",
    cadence: "hourly full-disk scan (push)",
    latency: "minutes",
    rateLimit: "none (object storage)",
    coverage: "satellite sea surface temperature, hourly, from the full disk centred on 75.2° W: all four areas (Florida Keys, Mexican Caribbean, Belize, Colombian Caribbean) are inside it; there is no CONUS SST sector",
    limits: ["cloud gaps", "skin temperature from a satellite: a buoy can disagree, and only Florida has sea-temperature buoys to check it"],
    tells: "hourly satellite sea surface temperature where clouds allow",
    sayAs: "GOES-19 SST (full disk)",
  },
  crw: {
    feed: "crw",
    publisher: "NOAA Coral Reef Watch (CoralTemp v3.1 daily global 5 km heat stress products, served by PacIOOS ERDDAP)",
    apiUrl: "https://pae-paha.pacioos.hawaii.edu/erddap/griddap/dhw_5km.json (CRW_SST, CRW_SSTANOMALY, CRW_DHW, CRW_BAA)",
    pageUrl: "https://coralreefwatch.noaa.gov/product/5km/index.php",
    licence: "free to use without restriction, with credit to NOAA Coral Reef Watch and a citation of the dataset DOI https://doi.org/10.3390/rs12233856",
    attribution: "NOAA Coral Reef Watch, CoralTemp v3.1 5 km daily products; cite https://doi.org/10.3390/rs12233856",
    cadence: "daily product at 12:00Z; polled daily per reef pixel",
    latency: "about 1.7 days from the product day to availability, by design",
    rateLimit: "not published; ERDDAP etiquette, one small request per pixel per day",
    coverage: "SST (°C), SST anomaly (°C), degree heating weeks (DHW, °C-weeks, accumulated over 12 weeks) and bleaching alert area level (BAA 0-4, current) at one 5 km pixel per reef in the four areas",
    limits: ["5 km pixel, one value per day: a reef inside a cloudy pixel can be masked (missing)", "DHW accumulates past heat; BAA needs a current HotSpot of at least 1 °C, so the two can disagree and are always shown together", "heat stress is context for where reefs are under pressure, not proof of lionfish damage"],
    tells: "how much accumulated heat stress a reef has had and whether it is under a bleaching alert now; context for survey planning, never a lionfish signal",
    sayAs: "NOAA Coral Reef Watch (CRW)",
  },
  nws: {
    feed: "nws",
    publisher: "NOAA National Weather Service (api.weather.gov)",
    apiUrl: "https://api.weather.gov/alerts/active",
    pageUrl: "https://www.weather.gov/documentation/services-web-api",
    licence: "U.S. Government work, public domain",
    attribution: "NOAA National Weather Service",
    cadence: "polled every minute",
    latency: "minutes",
    rateLimit: "not published; a User-Agent header is required",
    coverage: "active alerts in the region",
    limits: ["no push without NWWS-OI"],
    tells: "whether an alert is in effect",
  },
};
